-- Applied to project dxcrgaeopbbcrwycakgb on 2026-08-08.
create type public.lead_status as enum ('pending_review','eligible','contacted','responded','opted_out','invalid','blocked');
create type public.campaign_status as enum ('draft','scheduled','running','paused','completed','cancelled');
create type public.job_status as enum ('queued','processing','sent','failed','cancelled','skipped');
create table public.profiles (id uuid primary key references auth.users(id) on delete cascade, role text not null default 'viewer' check (role in ('owner','operator','viewer')), display_name text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.lead_imports (id uuid primary key default gen_random_uuid(), original_filename text not null, storage_path text not null, source text not null default 'google_places', imported_by uuid references auth.users(id), status text not null default 'uploaded' check (status in ('uploaded','processing','completed','failed')), total_rows integer not null default 0 check (total_rows >= 0), accepted_rows integer not null default 0 check (accepted_rows >= 0), rejected_rows integer not null default 0 check (rejected_rows >= 0), created_at timestamptz not null default now(), completed_at timestamptz);
create table public.leads (id uuid primary key default gen_random_uuid(), import_id uuid references public.lead_imports(id) on delete set null, external_place_id text, company_name text not null check (char_length(company_name) between 2 and 180), normalized_name text not null, phone_e164 text not null check (phone_e164 ~ '^\+[1-9][0-9]{7,14}$'), neighborhood text, city text, state char(2), source text not null, collected_at timestamptz not null default now(), legal_basis text not null, purpose text not null, status public.lead_status not null default 'pending_review', last_contacted_at timestamptz, opted_out_at timestamptz, deleted_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique (phone_e164));
create table public.lead_import_rows (id uuid primary key default gen_random_uuid(), import_id uuid not null references public.lead_imports(id) on delete cascade, row_number integer not null check (row_number > 0), raw_data jsonb not null, outcome text not null check (outcome in ('accepted','rejected','duplicate','pending_review')), reason text, lead_id uuid references public.leads(id) on delete set null, created_at timestamptz not null default now(), unique (import_id, row_number));
create table public.campaigns (id uuid primary key default gen_random_uuid(), name text not null check (char_length(name) between 2 and 140), message_template text not null check (char_length(message_template) between 1 and 4096), status public.campaign_status not null default 'draft', daily_limit integer not null default 0 check (daily_limit between 0 and 100), min_interval_seconds integer not null default 60 check (min_interval_seconds >= 60), created_by uuid not null references auth.users(id), scheduled_at timestamptz, started_at timestamptz, completed_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.campaign_recipients (id uuid primary key default gen_random_uuid(), campaign_id uuid not null references public.campaigns(id) on delete cascade, lead_id uuid not null references public.leads(id), status public.job_status not null default 'queued', created_at timestamptz not null default now(), unique (campaign_id, lead_id));
create table public.message_jobs (id uuid primary key default gen_random_uuid(), campaign_recipient_id uuid not null references public.campaign_recipients(id) on delete cascade, idempotency_key uuid not null default gen_random_uuid(), run_after timestamptz not null default now(), locked_at timestamptz, locked_by text, attempts integer not null default 0 check (attempts >= 0), status public.job_status not null default 'queued', last_error text, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique (idempotency_key));
create table public.message_attempts (id uuid primary key default gen_random_uuid(), message_job_id uuid not null references public.message_jobs(id) on delete cascade, provider_message_id text unique, outcome text not null check (outcome in ('accepted','sent','delivered','failed','cancelled','skipped')), error_code text, error_message text, attempted_at timestamptz not null default now());
create table public.inbound_messages (id uuid primary key default gen_random_uuid(), provider_message_id text not null unique, phone_e164 text not null check (phone_e164 ~ '^\+[1-9][0-9]{7,14}$'), message_text text not null, received_at timestamptz not null, raw_payload jsonb not null default '{}'::jsonb, created_at timestamptz not null default now());
create table public.opt_outs (id uuid primary key default gen_random_uuid(), phone_e164 text not null unique check (phone_e164 ~ '^\+[1-9][0-9]{7,14}$'), channel text not null default 'whatsapp', reason text, source text not null, created_at timestamptz not null default now());
create table public.audit_logs (id uuid primary key default gen_random_uuid(), actor_id uuid references auth.users(id) on delete set null, action text not null, entity_type text not null, entity_id text, metadata jsonb not null default '{}'::jsonb, created_at timestamptz not null default now());
create index leads_status_idx on public.leads(status) where deleted_at is null;
create index leads_import_id_idx on public.leads(import_id);
create index campaign_recipients_campaign_status_idx on public.campaign_recipients(campaign_id, status);
create index message_jobs_ready_idx on public.message_jobs(run_after) where status = 'queued';
create index message_attempts_job_idx on public.message_attempts(message_job_id);
create index inbound_messages_phone_idx on public.inbound_messages(phone_e164, received_at desc);
create or replace function public.set_updated_at() returns trigger language plpgsql security invoker set search_path = public as $$ begin new.updated_at = now(); return new; end; $$;
create trigger profiles_updated_at before update on public.profiles for each row execute procedure public.set_updated_at();
create trigger leads_updated_at before update on public.leads for each row execute procedure public.set_updated_at();
create trigger campaigns_updated_at before update on public.campaigns for each row execute procedure public.set_updated_at();
create trigger message_jobs_updated_at before update on public.message_jobs for each row execute procedure public.set_updated_at();
alter table public.profiles enable row level security;
alter table public.lead_imports enable row level security;
alter table public.leads enable row level security;
alter table public.lead_import_rows enable row level security;
alter table public.campaigns enable row level security;
alter table public.campaign_recipients enable row level security;
alter table public.message_jobs enable row level security;
alter table public.message_attempts enable row level security;
alter table public.inbound_messages enable row level security;
alter table public.opt_outs enable row level security;
alter table public.audit_logs enable row level security;
create policy profiles_read_own on public.profiles for select to authenticated using (id = auth.uid());
create policy profiles_update_own on public.profiles for update to authenticated using (id = auth.uid()) with check (id = auth.uid() and role = (select role from public.profiles where id = auth.uid()));
